# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table

# see: https://terraform-docs.io/user-guide/configuration/sections
sections:
  hide: 
    - modules
    - requirements
  show: []